project_name: 'ForestClassifier'
experiment_name: 'train_exp_v1.3'
random_seed: 1234

accelerator: 'cuda'
device: 1

n_epochs: 20
num_classes: 17

model_kwargs:
  model_name: 'resnet50'
  pretrained: true

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-2
  weight_decay: 1e-5

scheduler: 'torch.optim.lr_scheduler.ExponentialLR'
scheduler_kwargs:
  gamma: 0.85

losses:
  - name: 'bce'
    weight: 1
    loss_fn: 'torch.nn.BCEWithLogitsLoss'
    loss_kwargs: {}

data_config:
  dataset_path: 'data/datasets/planet'
  batch_size: 72
  n_workers: 8
  train_fraq: 0.8
  width: 256
  height: 256

monitor_metric: 'val_AP'
monitor_mode: 'max'
